# Generated by Django 2.1 on 2018-09-09 16:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('visuals', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='infecto',
            name='clinical',
        ),
        migrations.AddField(
            model_name='infecto',
            name='clinical',
            field=models.ForeignKey(default='not yet assigned', on_delete=django.db.models.deletion.CASCADE, to='visuals.Clinical'),
            preserve_default=False,
        ),
    ]
