# Generated by Django 2.1 on 2018-09-09 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visuals', '0002_auto_20180909_1645'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='infecto',
            name='clinical',
        ),
        migrations.AddField(
            model_name='infecto',
            name='clinical',
            field=models.ManyToManyField(to='visuals.Clinical'),
        ),
    ]
